#!/usr/bin/perl
print "oh don't run this\n"; exit(1);

#
# This is a perl file only so we can use
# pod2man on it. What a hoot!
#
# It uses the source file name, though, so we
# give it this name.
#

=head1 NAME

qt_atom 

=head1 SYNOPSIS

B<qt_atom> [settings-file]

=head1 DESCRIPTION

B<qt_atom> is a command line tool that
disassembles the contents a settings file
generated by qt_export. This is primarily
a debugging tool.

=head1 SEE ALSO

qt_tools(1),
qt_export(1), qt_atom(1), qt_thing(1)

=head1 AUTHOR and LICENSE

David Van Brink, email poly@omino.com , subject line must begin with "quicktime".

This software is provided as-is, &c.

This software is B<FREEWARE>. There is no compensation expected. In
return, I'll try to fix bugs if you find them. Hope that's ok with you.

=cut

# end of file
